apiVersion: batch/v1
kind: Job
metadata:
  name: csr-training
  labels:
    app: csr-training
spec:
  template:
    metadata:
      labels:
        app: csr-training
    spec:
      containers:
        - name: csr-training
          image: benedick/csr-training:latest
          env:
            - name: MLFLOW_TRACKING_USERNAME
              value: "$MLFLOW_TRACKING_USERNAME"
            - name: MLFLOW_TRACKING_PASSWORD
              value: "$MLFLOW_TRACKING_PASSWORD"
            - name: MLFLOW_EXPERIMENT_ID
              value: "$MLFLOW_EXPERIMENT_ID"
            - name: MLFLOW_TRACKING_URI
              value: "$MLFLOW_TRACKING_URI"
            - name: MINIO_ACCESS_KEY
              value: "$MINIO_ACCESS_KEY"
            - name: MINIO_ENDPOINT
              value: "$MINIO_ENDPOINT"
            - name: MINIO_SECRET_KEY
              value: "$MINIO_SECRET_KEY"
            - name: SSH_DEPLOY_KEY
              value: $SSH_DEPLOY_KEY
          resources:
            limits:
              nvidia.com/mig-2g.10gb: 1
            requests:
              cpu: 4
          command: ["./train_in_k8s.sh"]
      restartPolicy: Never
  backoffLimit: 4
